src/tui/editor.zig

using std.mem.split is a compileError as off this change
https://github.com/ziglang/zig/commit/76fb2b685b202ea665b850338e353c7816f5b2bb

split is a deprecated compile error and unused

---

src/syntax/src/file_types.zig

`ocamlformat` and `ocamllsp`, respectively. I engaged some "maximally correct" options.

Add OCaml Formatter and LS

---

src/renderer/vaxis/renderer.zig
src/tui/editor.zig
src/tui/mode/input/vim/insert.zig
src/tui/mode/input/vim/normal.zig
src/tui/mode/input/vim/visual.zig
src/tui/tui.zig

In vim mode, change the cursor shape depending on the mode. This is only
applicable if `enable_terminal_cursor` is set to true and there is only
one cursor in the editor.

vim: change cursor shape when only one cursor

---

src/tui/status/clock.zig

Pass the timezone as part of the `instant` call.

clock: simplify zeit usage

---

src/tui/mode/mini/open_file.zig

When opening a file, if one writes only "/" then presses ctrl+backspace the "path" slice will end up [0 .. -1].
This crashes in debug build, and possibly in some rare circumstances in release build.

open_file: fix possible underflow in delete_to_previous_path_segment

---

src/tui/editor.zig

erroring here could be problematic for scripting which already causes `:wq` to not actually exit

dont error on empty saves

---

zig

Removes a few bashisms like `==` in `test` and `$(<file)`, as well as changing the shebang. Feel free to close this without merging if you don't care, since multiple external tools are required anyway (however, I don't know how many FreeBSD users have bash installed).

Convert the zig wrapper to POSIX shell

---

src/tui/mode/input/helix/insert.zig
src/tui/mode/input/helix/normal.zig
src/tui/mode/input/helix/select.zig
src/tui/mode/input/vim/insert.zig
src/tui/mode/input/vim/normal.zig
src/tui/mode/input/vim/visual.zig

nvim binds this by default for hover
dont think you use `w` to quit :upside_down_face:

add vim normal hover keybind and fix typo

---

build.zig
build.zig.zon
src/main.zig

This changes the library used for command-line argument parsing from zig-clap to [flags](https://github.com/n0s4/flags/).
Disclaimer: I wrote flags, so I have some personal interest in getting feedback/real world usage.
Error messages are much more friendly and descriptive:
<details><summary>Old Error Messages (click to view)</summary>
<p>
</p>
</details> 
<details><summary>New Error Messages (click to view)</summary>
<p>
</p>
</details> 
The help message now has a full usage expression, description and terminal colors!
<details><summary>Old Help (click to view)</summary>
<p>
</p>
</details> 
<details><summary>New Help (click to view)</summary>
<p>
</p>
</details>
Flags also does not use heap allocation.
The actual usage of flags compared to zig-clap is quite similar, but a couple of …

Replace 'zig-clap' with 'flags'

---

src/win32/gui.zig

I left in two methods of aligning cells, either on the pixel boundary or not. There's tradeoffs for both, not sure if one is strictly better than the other so I just left both in for now.

win32 gui: fix some issues with cell sizing/alignment

---

src/win32/gui.zig

Allows us to define a default initial placement/size of the GUI window.  We could use a ratio of the screen but for now I'm just using a hardcoded size of `800x1200` logical pixels (scaled up as DPI increases).  It's also centering it on the monitor and keeping the window in the "work area" of the montor (inside the viewable area and not behind the taskbar).  This also enables a future change to allow the user to specify the initial window size/location on the command-line.

win32 gui: implement window placement and higher DPI icons

---

src/win32/gui.zig

woops, accidently broke the window icon by moving the code that loads it after calling RegisterClass, here's the fix

win32 gui: unbreak window icon

---

src/keybind/builtin/emacs.json
src/keybind/keybind.zig
src/keybind/parse_flow.zig
src/keybind/parse_vim.zig
src/renderer/vaxis/input.zig
src/tui/inputview.zig
src/win32/gui.zig

I played around with the API a bit and I tried out the other approach where instead of trying to implement our own keyboard translation, instead I just clear the "control key" before calling ToUnicode.  This fixes any weird translation the OS was doing.
With this change, we no longer need to skip calling ToUnicode if the control or alt keys are down, so keys will always work the same way whether or not these modifiers are down.
P.S. this seems to bring the win32 GUI inline with the WindowsTerminal in how it handles input.   For example, pressing `alt+shift+.` (where `.` is the `.>` key on my keyboard) will produce the `>` character in both Windows Terminal and the GUI now.

win32 gui: remove bespoke/incorrect key translation

---

src/buffer/Cursor.zig
src/keybind/builtin/helix.json
src/tui/editor.zig

I've added half page movements and changed the command for page up/down in select mode.
It's not an one-to-one replica of helix's movements, there's a few minor differences such as clamping and how page up&down is calculated. If fidelity is a must I'll make the necessary changes, just let me know.

Helix mode half and whole page movements

---

src/keybind/builtin/emacs.json
src/win32/gui.zig

https://github.com/user-attachments/assets/f45089e3-206d-4599-a700-7891f2f48aa4
https://github.com/user-attachments/assets/5355ce63-8188-4d8a-92c0-7fe1ce500405

win32 gui: track and use window bounds to prevent infinite shrinkage

---

src/keybind/builtin/flow.json

after looking into addressing the part of #141 actively bothering me, I found out that the modifiers for the mouse commands aren't queried directly, rather by which mode is currently active. This change swaps the `fast_scroll` and `jump_mode` keybinds, which in turn makes the `goto_definition` and `add_cursor` mouse actions behave like VSCode. This might already be enough to close the issue, since I don't know of other editors that allow mouse behavior rebinding.

swap enable_fast_scroll and enable_jump_mode keybinds

---

src/win32/builtin.hlsl
src/win32/d3d11.zig
src/win32/gui.zig

Changes d3d11 to accept an array of cells to render that have already been rendered to a texture and converted to texture coordinates.  This minimizes the time we have to map the shader cell buffer which blocks the GPU from using it.

direct3d: hoist flow types out, provide cell type, don't block GPU

---

src/win32/DwriteRenderer.zig
src/win32/d3d11.zig

I tried adding Andrew's TrueType renderer as an option, however, I realized it doesn't work with zig 0.13.0, so it'll have to wait.
Until then here's the changes needed to decouple the screen/text rendering which would make it easier to add more text renderers and just cleans things up a bit more in general.

win32 gui: decouple screen renderer from text renderer

---

src/syntax/build.zig
src/syntax/build.zig.zon
src/syntax/src/file_types.zig

This depends on https://github.com/neurocyte/tree-sitter/pull/8. Marked as draft because the `tree-sitter` dep url and hash will need to be updated before this builds.

add systemverilog lsp and formatter

---

src/win32/gui.zig

Looks like I probably accidently removed the calls to BeginPaint and EndPaint in WM_PAINT, which, would cause the OS to think that the window contents are never validated and will continuously send us WM_PAINT messages.  I've added these back in and now flow is back to low CPU usage especially when idle.

win32 gui: fix high cpu usage, validate window in WM_PAINT

---

build.zig
build.zig.zon
src/renderer/win32/renderer.zig
src/win32/gui.zig
src/win32/win32ext.zig

Since we removed the direct2d renderer we no longer need to reference the direct2d-zig repository.  Instead we now directly reference the zigwin32 repository.  I've also updated that repository with a few fixes and additions which allowed us to remove some code from flow.

remove direct2d dependency and update zigwin32

---

build.zig
src/buffer/Selection.zig
src/keybind/builtin/helix.json
src/keybind/keybind.zig
src/tui/editor.zig
src/tui/tui.zig

Here's my take on how to tweak tui/editor.zig to get cursors and selections playing nice with helix mode.
Still have to add commands like moving left and right to mimic the behavior in helix, especially when text is selected and we're moving out of that.

Develop `helix_mode` internals and basic commands

---

src/renderer/vaxis/renderer.zig

the current code causes the call to panic itself to show up in the stack trace which is noisy
before:
```
thread 17618 panic: oopsies
/home/jonah/dev/flow/src/renderer/vaxis/renderer.zig:90:37: 0x107cd06 in panic (flow)
return std.builtin.default_panic(msg, error_return_trace, ret_addr);
^
/home/jonah/dev/flow/src/main.zig:38:15: 0x107d0e0 in main (flow)
if (true) @panic("oopsies");
^
/home/jonah/dev/ghostty/zig-linux-x86_64-0.13.0/lib/std/start.zig:524:37: 0x107cba7 in main (flow)
const result = root.main() catch |err| {
^
```
after:
```
thread 18109 panic: oopsies
/home/jonah/dev/flow/src/main.zig:38:15: 0x107d140 in main (flow)
if (true) @panic("oopsies");
^
/home/jonah/dev/ghostty/zig-linux-x86_64-0.13.0/lib/std/start.zig:524:37: 0x107cba7 in main (flow)
const result = root.main() …
```

use @returnAddress in panic handler

---

src/keybind/builtin/vim.json

Currently, pressing `j` while in INSERT mode in the Vim input mode waits for another key to be pressed. Pressing any key after pressing `j` would write `j<whatever key was pressed>`, and pressing `k` after `j` would exit INSERT mode.
This fixes that by removing the `jk` keybinding from `vim.json`, as it is entirely unnecessary, and is not like this at all in the actual Vim.

Remove 'jk' keybinding in Vim's INSERT mode

---

src/keybind/builtin/vim.json
src/tui/editor.zig

Removed the possibility of the cursor being in the `LF` position in **NORMAL** mode (for the most part, some cases are more complicated, but should be fine :)). This was accomplished by replacing the vertical movement commands with VIM counterparts that check for an `LF` after the movement was performed.
Added simple indent and unindent bindings.
Added Visual Line mode, with corresponding bindings, mostly from already existing commands.
Replaced `delete_to_end` commands with `cut_to_end` commands.
Replaced `move_scroll_page_up` and `move_scroll_page_down` with half scroll commands instead, for more accurate VIM behaviour.
Added `c`, `C` keybinds and some other small things I can't remember now.

More vim bindings, visual line mode, QOL vim things

---

src/bin_path.zig
src/syntax/src/file_types.zig

Hi,
Some LSPs that I run on Windows installed through npm have the `.cmd` extension as opposed to `.exe` (like `intelephense.cmd` that I sent a PR for in https://github.com/neurocyte/flow/pull/186).
This is a small change, but I'm new to Zig, so if there's a better way or if there are any issues do let me know.
Thanks!

Allow .cmd along with .exe for Windows paths

---

src/keybind/builtin/flow.json

"project" bindings are inherited by the "home" screen, but the command inserts into a buffer, hence fails with an error.

mv alt+R binding from project to normal keymap

---

src/tui/mode/overlay/open_recent.zig

Hi,
I noticed that page up/down showed an error for the "open recent file" overlay. After reading the code I understand that paging doesn't make much sense since only the first 25 files are shown and the list content is dynamically changed when typing. Either way, I think jumping with page up/down to the start/end of the menu is better than showing `CommandNotFound: menu_page_up`/down.

fix: open recent file ignoring page up/down

---

src/tui/editor.zig

I didn't find a way to use flow when I have to do a minor edit to a file that has legacy formatting, except by uninstalling the formatting tool.

feat: save file without formatting

---

src/keybind/builtin/helix.json
src/tui/editor.zig
src/tui/mode/helix.zig

This PR aims to implement or correct the following helix commands:
When all the list commands are implemented, the PR will be marked as Ready for review.
Related issue: #206

Helix mode: adding commands

---

src/keybind/builtin/helix.json
src/tui/editor.zig

Currently the Helix normal mode uses the `cut` function for the `d` and `c` bindings:
https://github.com/neurocyte/flow/blob/b30a5d4819ca2b7e8835d8fe18aa4956f61a5a83/src/keybind/builtin/helix.json#L149-L150
...which leads to unintended behavior because that deletes the whole line. Looking at the Vim bindings for the `x` binding, which has a similar behavior, it is used the `cut_forward_internal` function. Trying to use this same function for the helix `d` and `c` actions also leads to unintended behaviors because it deletes both the character under the cursor and the next as result of the `inclusive_selection`. So this PR adds a switch statement to the `cut_to` function, used by the `cut_forward_internal` function, to handle the `inclusive_selection` of helix so it can be use properly on …

fix(helix): Making `d` and `c` work as expected in normal mode

---

src/tui/mode/helix.zig

Turns out that `selection = null` was the right approach. `.disable_selection` preserves selected the char originally under cursor, which is not the intended behavior.

fix move_next_word_end

---

src/keybind/builtin/helix.json
src/tui/editor.zig
src/tui/mode/helix.zig

Bugs addressed:
- Pasting whole lines only works when the cursor is at the end of line
- Delete in select mode do not enter normal mode
- `c` keymap in normal mode without selection do not deletes the char under cursor

Helix mode fixes

---

src/keybind/builtin/helix.json

Changed the builtin helix keybindings that incorrectly used `shift` in its sequence. All changed cases have been tested manually to trigger the correct command, although no test cases have been written.

Fixed helix keybinds that used `shift` in sequence incorrectly

---

src/tui/mode/overlay/palette.zig

Fixes the palette crashing when input exceeding its longest item by expanding the input box.

Fix: Assert hit when exceeding inputbox's item's length in palette.zig.

---

src/tui/status/selectionstate.zig

I was initially confused about "(4 selected)" in the status bar -- 4 "what"?  Especially because often, it is preceded by "(N matches)".
This harmonizes the display of an in-line selection with the multi-line case, and shows that it's a certain number of "chars" that are selected.

harmonize selection display

---

src/syntax/src/file_types.zig

The former is the canonical executable name, and also what Helix uses. Seems reasonable to standardize on that.

`file_types`: invoke `OmniSharp` instead of `omnisharp`

---

README.md

Two of the code blocks were missing `shell`

Add missing `shell`s to the README

---

help.md
src/buffer/Manager.zig
src/tui/mainview.zig
src/tui/mode/helix.zig

* `:rla` reload all buffers
* `:bco` close other buffers except current
* `:bco!` close all the other buffers even without saved changes
* `:x` saves this buffer and exit if all the others can be closed
* `:x!` saves the current buffer and exit discarding all others changes, if any
We need some mechanism to tell the user why something failed, for example: `:x` can fail, but `:x!` shouldn't.  The following screenshot shows how Helix let the user know that something impeded an action to shoot the foot themselves... .  Maybe a miss on my side if there is one that I didn't see, please point me to the place to put the necessary and I will add corresponding messages in some places.

feat: add helix mode close other buffers and reload all
